Support registries in gzipped tarballs
JuliaEcosystem/PkgDeps.jl pull request #38
Opened 2022-05-26 18:21 UTC by danielmatz

Starting with Julia 1.7, a registry can also be stored in a depot as a
gzipped tarball. This commit unpacks the tarball into a temporary
directory. This was the simplest way to support this new feature.

This implementation will unpack a fresh copy of the registry on every
call to `reachable_registries`. We could instead cache the temporary
directory for future calls.

There's an open PR for the Tar.jl package that will be of future
interest:

https://github.com/JuliaIO/Tar.jl/pull/95

This would allow us to instead stream the individual files straight
out of the tarball, rather than having to unpack it into a temporary
location.

2022-06-01 16:56 UTC, giordano requested changes
I don't think this is a good approach.  Pkg has its own API to analyse registries, whether they are gzipped or not, should use that instead

2022-06-01 18:56 UTC, danielmatz commented
> I don't think this is a good approach. Pkg has its own API to analyse registries, whether they are gzipped or not, should use that instead

Yes, I see Pkg has a `Pkg.Registry.reachable_registries` function as of Julia 1.7.

Are you proposing that this package require Julia 1.7 or newer and remove its duplicate implementations of the registry-related code?

Or should I detect the Julia version and use the Pkg API if available, and otherwise fall back to the existing registry code in PkgDeps, which would not support tarballs?

2022-06-01 19:05 UTC, giordano commented
I guess that's a question for @mattBrzezinski.  The question boils down to whether supporting julia v1.6 is important, or we can drop it and move to v1.7+ only.  We have a [similar situation](https://github.com/JuliaEcosystem/PackageAnalyzer.jl/issues/67) in PackageAnalyzer, there I'd be ok with dropping v1.6 and moving to v1.7+ only.

2022-06-01 19:44 UTC, danielmatz commented
OK, I made a new PR with the approach of requiring Julia 1.7. See #39.

2022-06-16 19:40 UTC, mattBrzezinski commented
> I guess that's a question for @mattBrzezinski. The question boils down to whether supporting julia v1.6 is important, or we can drop it and move to v1.7+ only. We have a [similar situation](https://github.com/JuliaEcosystem/PackageAnalyzer.jl/issues/67) in PackageAnalyzer, there I'd be ok with dropping v1.6 and moving to v1.7+ only.

I would prefer to maintain support for LTS versions of Julia.

2022-06-21 15:12 UTC, danielmatz commented
Well, the LTS version of Julia won't create gzipped tarballs. I bumped the julia compat entry in my other PR. So, I suppose we could release v0.7 of this package, which would require Julia 1.7, while maintaining v0.6 for the LTS version of Julia?

Alternatively, I could rework my PR so that it uses the Pkg API for Julia 1.7+, but gracefully falls back to your existing code for the LTS.

2022-06-21 15:32 UTC, mattBrzezinski commented
> 

We could instead do something nifty like [this](https://github.com/invenia/LibPQ.jl/blob/e94033cbfd19c07269f5636838221beb2a4a67d8/src/parsing.jl#L298) to handle the differences between versions!

2022-06-22 22:59 UTC, danielmatz commented
OK, I took a stab at it in my other PR.

2022-12-20 21:20 UTC, danielmatz commented
Closing this in favor of #42.

2022-12-20 21:20 UTC, closed without merging